### ISSUE TITLE
Entities unavailable

### ISSUE THREAD

**Issue by mdorchain** [DigitallyRefined/ha-cloudflare-speed-test#12]
Hi, first thanks for the integration :) I just love it.

It works great overall, however I found a some small issue.
Periodically, all entities are becoming unavailable. This reflects by 70min gaps in the history graph.

![Image](https://github.com/user-attachments/assets/ba88e9e2-f523-48db-91cb-39f5b79d14ca)

Also It would have been great if we could get the server location as entity/entites, since it seems to be available in cloudflarepycli, unlike the packet loss %.

Thanks again.

Michael

**Comment by DigitallyRefined** [comment]
I've not seen this issue with data becoming unavailable on my install I've tested (2025.03 to 2025.05):

<img width="562" alt="Image" src="https://github.com/user-attachments/assets/163a1e9b-64d6-4ebc-9b82-e58239bb4df1" />

The only change I've made to my install is to only update/run a speed test every 24 hours, by going into the integration settings and disabling "Enable polling for changes" (otherwise by default this runs a new speed test every hour)

<img width="1012" alt="Image" src="https://github.com/user-attachments/assets/8301dbba-44f6-4af8-ae24-00639b23816a" />

Then I use the following automation to trigger it automatically daily (note that you only need to call update on one of the entities and this will update all of them):

```yaml
alias: Run Speed Test
description: ""
triggers:
  - hours: "0"
    minutes: "4"
    seconds: "6"
    trigger: time_pattern
conditions: []
actions:
  - action: homeassistant.update_entity
    target:
      entity_id: sensor.cloudflare_speed_test_90th_percentile_down
    data: {}
mode: single
```

This integration is a fork of the [Speedtest.net integration](https://www.home-assistant.io/integrations/speedtestdotnet/), so it may be worth seeing if the same issue happens with the original Home Assistant integration first, as it could be an upstream issue.

Server city, region and code is added to each of the sensors as an attribute, which you can click on to expand in the UI or if you want to use it on your dashboard you can use an entities card:

```yaml
type: entities
entities:
  - type: attribute
    entity: sensor.cloudflare_speed_test_90th_percentile_down
    attribute: server_city
  - type: attribute
    entity: sensor.cloudflare_speed_test_90th_percentile_down
    attribute: server_region
  - type: attribute
    entity: sensor.cloudflare_speed_test_90th_percentile_down
    attribute: server_code
```

Or use it in a template via `state_attr`:

```yaml
{{ state_attr('sensor.cloudflare_speed_test_90th_percentile_down', 'server_city') }}
{{ state_attr('sensor.cloudflare_speed_test_90th_percentile_down', 'server_region') }}
{{ state_attr('sensor.cloudflare_speed_test_90th_percentile_down', 'server_code') }}
```
